Replace bucket content instead of adding

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -29,13 +29,14 @@ jobs:
         run: yarn test
       - name: Build
         run: yarn build
+      - name: Validate directory not empty
+        run: '[ "$(ls -A ./build)" ] && echo "Files exist - all good." || (echo "Directory is empty - aborting." && exit 1)'
       - id: 'auth'
+        name: Authenticate to Google Cloud
         uses: 'google-github-actions/auth@v0'
         with:
           credentials_json: '${{ secrets.GCP_CREDENTIALS_LIVE }}'
-      - name: Upload index.html to Google Cloud Storage bucket
-        uses: google-github-actions/upload-cloud-storage@main
-        with:
-          path: build
-          destination: geeffektivt-se-frontend-ec5e8b5
-          parent: false
+      - name: Set up Cloud SDK
+        uses: 'google-github-actions/setup-gcloud@v0'
+      - name: Upload build folder to Google Cloud Storage bucket
+        run: 'gsutil rsync -d -r ./build gs://geeffektivt-se-frontend-ec5e8b5'
